// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_log.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5flog_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_5flog_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_5flog_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5flog_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[9]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5flog_2eproto;
namespace msg_log {
class CountLogAck;
struct CountLogAckDefaultTypeInternal;
extern CountLogAckDefaultTypeInternal _CountLogAck_default_instance_;
class CountLogReq;
struct CountLogReqDefaultTypeInternal;
extern CountLogReqDefaultTypeInternal _CountLogReq_default_instance_;
class LogRecord;
struct LogRecordDefaultTypeInternal;
extern LogRecordDefaultTypeInternal _LogRecord_default_instance_;
class QueryLogAck;
struct QueryLogAckDefaultTypeInternal;
extern QueryLogAckDefaultTypeInternal _QueryLogAck_default_instance_;
class QueryLogReq;
struct QueryLogReqDefaultTypeInternal;
extern QueryLogReqDefaultTypeInternal _QueryLogReq_default_instance_;
class SendLogAck;
struct SendLogAckDefaultTypeInternal;
extern SendLogAckDefaultTypeInternal _SendLogAck_default_instance_;
class SendLogBatchAck;
struct SendLogBatchAckDefaultTypeInternal;
extern SendLogBatchAckDefaultTypeInternal _SendLogBatchAck_default_instance_;
class SendLogBatchReq;
struct SendLogBatchReqDefaultTypeInternal;
extern SendLogBatchReqDefaultTypeInternal _SendLogBatchReq_default_instance_;
class SendLogReq;
struct SendLogReqDefaultTypeInternal;
extern SendLogReqDefaultTypeInternal _SendLogReq_default_instance_;
}  // namespace msg_log
PROTOBUF_NAMESPACE_OPEN
template<> ::msg_log::CountLogAck* Arena::CreateMaybeMessage<::msg_log::CountLogAck>(Arena*);
template<> ::msg_log::CountLogReq* Arena::CreateMaybeMessage<::msg_log::CountLogReq>(Arena*);
template<> ::msg_log::LogRecord* Arena::CreateMaybeMessage<::msg_log::LogRecord>(Arena*);
template<> ::msg_log::QueryLogAck* Arena::CreateMaybeMessage<::msg_log::QueryLogAck>(Arena*);
template<> ::msg_log::QueryLogReq* Arena::CreateMaybeMessage<::msg_log::QueryLogReq>(Arena*);
template<> ::msg_log::SendLogAck* Arena::CreateMaybeMessage<::msg_log::SendLogAck>(Arena*);
template<> ::msg_log::SendLogBatchAck* Arena::CreateMaybeMessage<::msg_log::SendLogBatchAck>(Arena*);
template<> ::msg_log::SendLogBatchReq* Arena::CreateMaybeMessage<::msg_log::SendLogBatchReq>(Arena*);
template<> ::msg_log::SendLogReq* Arena::CreateMaybeMessage<::msg_log::SendLogReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg_log {

enum LogType : int {
  LOG_TYPE_LOGIN = 0,
  LOG_TYPE_LOGOUT = 1,
  LOG_TYPE_CREATE_ROLE = 2,
  LOG_TYPE_DELETE_ROLE = 3,
  LOG_TYPE_RECHARGE = 4,
  LOG_TYPE_CONSUME = 5,
  LOG_TYPE_ITEM = 6,
  LOG_TYPE_TRADE = 7,
  LOG_TYPE_BATTLE = 8,
  LOG_TYPE_TASK = 9,
  LOG_TYPE_GUILD = 10,
  LOG_TYPE_CHAT = 11,
  LOG_TYPE_ERROR = 12,
  LOG_TYPE_SYSTEM = 13,
  LogType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LogType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LogType_IsValid(int value);
constexpr LogType LogType_MIN = LOG_TYPE_LOGIN;
constexpr LogType LogType_MAX = LOG_TYPE_SYSTEM;
constexpr int LogType_ARRAYSIZE = LogType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogType_descriptor();
template<typename T>
inline const std::string& LogType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LogType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LogType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LogType_descriptor(), enum_t_value);
}
inline bool LogType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LogType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LogType>(
    LogType_descriptor(), name, value);
}
enum LogLevel : int {
  LOG_LEVEL_DEBUG = 0,
  LOG_LEVEL_INFO = 1,
  LOG_LEVEL_WARN = 2,
  LOG_LEVEL_ERROR = 3,
  LOG_LEVEL_FATAL = 4,
  LogLevel_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LogLevel_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LogLevel_IsValid(int value);
constexpr LogLevel LogLevel_MIN = LOG_LEVEL_DEBUG;
constexpr LogLevel LogLevel_MAX = LOG_LEVEL_FATAL;
constexpr int LogLevel_ARRAYSIZE = LogLevel_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogLevel_descriptor();
template<typename T>
inline const std::string& LogLevel_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LogLevel>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LogLevel_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LogLevel_descriptor(), enum_t_value);
}
inline bool LogLevel_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LogLevel* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LogLevel>(
    LogLevel_descriptor(), name, value);
}
// ===================================================================

class LogRecord final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg_log.LogRecord) */ {
 public:
  inline LogRecord() : LogRecord(nullptr) {}
  ~LogRecord() override;
  explicit constexpr LogRecord(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogRecord(const LogRecord& from);
  LogRecord(LogRecord&& from) noexcept
    : LogRecord() {
    *this = ::std::move(from);
  }

  inline LogRecord& operator=(const LogRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogRecord& operator=(LogRecord&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogRecord& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogRecord* internal_default_instance() {
    return reinterpret_cast<const LogRecord*>(
               &_LogRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LogRecord& a, LogRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(LogRecord* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogRecord* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogRecord>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogRecord& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const LogRecord& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogRecord* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg_log.LogRecord";
  }
  protected:
  explicit LogRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoleNameFieldNumber = 6,
    kContentFieldNumber = 7,
    kExtraDataFieldNumber = 8,
    kIpFieldNumber = 10,
    kLogIdFieldNumber = 1,
    kTypeFieldNumber = 2,
    kLevelFieldNumber = 3,
    kRoleIdFieldNumber = 5,
    kLogTimeFieldNumber = 9,
    kServerIdFieldNumber = 4,
  };
  // string role_name = 6;
  void clear_role_name();
  const std::string& role_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_role_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_role_name();
  PROTOBUF_NODISCARD std::string* release_role_name();
  void set_allocated_role_name(std::string* role_name);
  private:
  const std::string& _internal_role_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_role_name(const std::string& value);
  std::string* _internal_mutable_role_name();
  public:

  // string content = 7;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // string extra_data = 8;
  void clear_extra_data();
  const std::string& extra_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_extra_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_extra_data();
  PROTOBUF_NODISCARD std::string* release_extra_data();
  void set_allocated_extra_data(std::string* extra_data);
  private:
  const std::string& _internal_extra_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_extra_data(const std::string& value);
  std::string* _internal_mutable_extra_data();
  public:

  // string ip = 10;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // int64 log_id = 1;
  void clear_log_id();
  int64_t log_id() const;
  void set_log_id(int64_t value);
  private:
  int64_t _internal_log_id() const;
  void _internal_set_log_id(int64_t value);
  public:

  // .msg_log.LogType type = 2;
  void clear_type();
  ::msg_log::LogType type() const;
  void set_type(::msg_log::LogType value);
  private:
  ::msg_log::LogType _internal_type() const;
  void _internal_set_type(::msg_log::LogType value);
  public:

  // .msg_log.LogLevel level = 3;
  void clear_level();
  ::msg_log::LogLevel level() const;
  void set_level(::msg_log::LogLevel value);
  private:
  ::msg_log::LogLevel _internal_level() const;
  void _internal_set_level(::msg_log::LogLevel value);
  public:

  // uint64 role_id = 5;
  void clear_role_id();
  uint64_t role_id() const;
  void set_role_id(uint64_t value);
  private:
  uint64_t _internal_role_id() const;
  void _internal_set_role_id(uint64_t value);
  public:

  // int64 log_time = 9;
  void clear_log_time();
  int64_t log_time() const;
  void set_log_time(int64_t value);
  private:
  int64_t _internal_log_time() const;
  void _internal_set_log_time(int64_t value);
  public:

  // int32 server_id = 4;
  void clear_server_id();
  int32_t server_id() const;
  void set_server_id(int32_t value);
  private:
  int32_t _internal_server_id() const;
  void _internal_set_server_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg_log.LogRecord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr role_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr extra_data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
  int64_t log_id_;
  int type_;
  int level_;
  uint64_t role_id_;
  int64_t log_time_;
  int32_t server_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5flog_2eproto;
};
// -------------------------------------------------------------------

class SendLogReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg_log.SendLogReq) */ {
 public:
  inline SendLogReq() : SendLogReq(nullptr) {}
  ~SendLogReq() override;
  explicit constexpr SendLogReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendLogReq(const SendLogReq& from);
  SendLogReq(SendLogReq&& from) noexcept
    : SendLogReq() {
    *this = ::std::move(from);
  }

  inline SendLogReq& operator=(const SendLogReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendLogReq& operator=(SendLogReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendLogReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendLogReq* internal_default_instance() {
    return reinterpret_cast<const SendLogReq*>(
               &_SendLogReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SendLogReq& a, SendLogReq& b) {
    a.Swap(&b);
  }
  inline void Swap(SendLogReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendLogReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendLogReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendLogReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendLogReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SendLogReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendLogReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg_log.SendLogReq";
  }
  protected:
  explicit SendLogReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecordFieldNumber = 1,
  };
  // .msg_log.LogRecord record = 1;
  bool has_record() const;
  private:
  bool _internal_has_record() const;
  public:
  void clear_record();
  const ::msg_log::LogRecord& record() const;
  PROTOBUF_NODISCARD ::msg_log::LogRecord* release_record();
  ::msg_log::LogRecord* mutable_record();
  void set_allocated_record(::msg_log::LogRecord* record);
  private:
  const ::msg_log::LogRecord& _internal_record() const;
  ::msg_log::LogRecord* _internal_mutable_record();
  public:
  void unsafe_arena_set_allocated_record(
      ::msg_log::LogRecord* record);
  ::msg_log::LogRecord* unsafe_arena_release_record();

  // @@protoc_insertion_point(class_scope:msg_log.SendLogReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::msg_log::LogRecord* record_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5flog_2eproto;
};
// -------------------------------------------------------------------

class SendLogAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg_log.SendLogAck) */ {
 public:
  inline SendLogAck() : SendLogAck(nullptr) {}
  ~SendLogAck() override;
  explicit constexpr SendLogAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendLogAck(const SendLogAck& from);
  SendLogAck(SendLogAck&& from) noexcept
    : SendLogAck() {
    *this = ::std::move(from);
  }

  inline SendLogAck& operator=(const SendLogAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendLogAck& operator=(SendLogAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendLogAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendLogAck* internal_default_instance() {
    return reinterpret_cast<const SendLogAck*>(
               &_SendLogAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SendLogAck& a, SendLogAck& b) {
    a.Swap(&b);
  }
  inline void Swap(SendLogAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendLogAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendLogAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendLogAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendLogAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SendLogAck& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendLogAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg_log.SendLogAck";
  }
  protected:
  explicit SendLogAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogIdFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // int64 log_id = 2;
  void clear_log_id();
  int64_t log_id() const;
  void set_log_id(int64_t value);
  private:
  int64_t _internal_log_id() const;
  void _internal_set_log_id(int64_t value);
  public:

  // int32 result = 1;
  void clear_result();
  int32_t result() const;
  void set_result(int32_t value);
  private:
  int32_t _internal_result() const;
  void _internal_set_result(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg_log.SendLogAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int64_t log_id_;
  int32_t result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5flog_2eproto;
};
// -------------------------------------------------------------------

class SendLogBatchReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg_log.SendLogBatchReq) */ {
 public:
  inline SendLogBatchReq() : SendLogBatchReq(nullptr) {}
  ~SendLogBatchReq() override;
  explicit constexpr SendLogBatchReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendLogBatchReq(const SendLogBatchReq& from);
  SendLogBatchReq(SendLogBatchReq&& from) noexcept
    : SendLogBatchReq() {
    *this = ::std::move(from);
  }

  inline SendLogBatchReq& operator=(const SendLogBatchReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendLogBatchReq& operator=(SendLogBatchReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendLogBatchReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendLogBatchReq* internal_default_instance() {
    return reinterpret_cast<const SendLogBatchReq*>(
               &_SendLogBatchReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SendLogBatchReq& a, SendLogBatchReq& b) {
    a.Swap(&b);
  }
  inline void Swap(SendLogBatchReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendLogBatchReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendLogBatchReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendLogBatchReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendLogBatchReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SendLogBatchReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendLogBatchReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg_log.SendLogBatchReq";
  }
  protected:
  explicit SendLogBatchReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecordsFieldNumber = 1,
  };
  // repeated .msg_log.LogRecord records = 1;
  int records_size() const;
  private:
  int _internal_records_size() const;
  public:
  void clear_records();
  ::msg_log::LogRecord* mutable_records(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord >*
      mutable_records();
  private:
  const ::msg_log::LogRecord& _internal_records(int index) const;
  ::msg_log::LogRecord* _internal_add_records();
  public:
  const ::msg_log::LogRecord& records(int index) const;
  ::msg_log::LogRecord* add_records();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord >&
      records() const;

  // @@protoc_insertion_point(class_scope:msg_log.SendLogBatchReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord > records_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5flog_2eproto;
};
// -------------------------------------------------------------------

class SendLogBatchAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg_log.SendLogBatchAck) */ {
 public:
  inline SendLogBatchAck() : SendLogBatchAck(nullptr) {}
  ~SendLogBatchAck() override;
  explicit constexpr SendLogBatchAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendLogBatchAck(const SendLogBatchAck& from);
  SendLogBatchAck(SendLogBatchAck&& from) noexcept
    : SendLogBatchAck() {
    *this = ::std::move(from);
  }

  inline SendLogBatchAck& operator=(const SendLogBatchAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendLogBatchAck& operator=(SendLogBatchAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendLogBatchAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendLogBatchAck* internal_default_instance() {
    return reinterpret_cast<const SendLogBatchAck*>(
               &_SendLogBatchAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SendLogBatchAck& a, SendLogBatchAck& b) {
    a.Swap(&b);
  }
  inline void Swap(SendLogBatchAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendLogBatchAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendLogBatchAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendLogBatchAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendLogBatchAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SendLogBatchAck& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendLogBatchAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg_log.SendLogBatchAck";
  }
  protected:
  explicit SendLogBatchAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
    kSuccessCountFieldNumber = 2,
    kFailedCountFieldNumber = 3,
  };
  // int32 result = 1;
  void clear_result();
  int32_t result() const;
  void set_result(int32_t value);
  private:
  int32_t _internal_result() const;
  void _internal_set_result(int32_t value);
  public:

  // int32 success_count = 2;
  void clear_success_count();
  int32_t success_count() const;
  void set_success_count(int32_t value);
  private:
  int32_t _internal_success_count() const;
  void _internal_set_success_count(int32_t value);
  public:

  // int32 failed_count = 3;
  void clear_failed_count();
  int32_t failed_count() const;
  void set_failed_count(int32_t value);
  private:
  int32_t _internal_failed_count() const;
  void _internal_set_failed_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg_log.SendLogBatchAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t result_;
  int32_t success_count_;
  int32_t failed_count_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5flog_2eproto;
};
// -------------------------------------------------------------------

class QueryLogReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg_log.QueryLogReq) */ {
 public:
  inline QueryLogReq() : QueryLogReq(nullptr) {}
  ~QueryLogReq() override;
  explicit constexpr QueryLogReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QueryLogReq(const QueryLogReq& from);
  QueryLogReq(QueryLogReq&& from) noexcept
    : QueryLogReq() {
    *this = ::std::move(from);
  }

  inline QueryLogReq& operator=(const QueryLogReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryLogReq& operator=(QueryLogReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryLogReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryLogReq* internal_default_instance() {
    return reinterpret_cast<const QueryLogReq*>(
               &_QueryLogReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(QueryLogReq& a, QueryLogReq& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryLogReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryLogReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryLogReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QueryLogReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QueryLogReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const QueryLogReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryLogReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg_log.QueryLogReq";
  }
  protected:
  explicit QueryLogReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kServerIdFieldNumber = 2,
    kRoleIdFieldNumber = 3,
    kStartTimeFieldNumber = 4,
    kEndTimeFieldNumber = 5,
    kLimitFieldNumber = 6,
    kOffsetFieldNumber = 7,
  };
  // .msg_log.LogType type = 1;
  void clear_type();
  ::msg_log::LogType type() const;
  void set_type(::msg_log::LogType value);
  private:
  ::msg_log::LogType _internal_type() const;
  void _internal_set_type(::msg_log::LogType value);
  public:

  // int32 server_id = 2;
  void clear_server_id();
  int32_t server_id() const;
  void set_server_id(int32_t value);
  private:
  int32_t _internal_server_id() const;
  void _internal_set_server_id(int32_t value);
  public:

  // uint64 role_id = 3;
  void clear_role_id();
  uint64_t role_id() const;
  void set_role_id(uint64_t value);
  private:
  uint64_t _internal_role_id() const;
  void _internal_set_role_id(uint64_t value);
  public:

  // int64 start_time = 4;
  void clear_start_time();
  int64_t start_time() const;
  void set_start_time(int64_t value);
  private:
  int64_t _internal_start_time() const;
  void _internal_set_start_time(int64_t value);
  public:

  // int64 end_time = 5;
  void clear_end_time();
  int64_t end_time() const;
  void set_end_time(int64_t value);
  private:
  int64_t _internal_end_time() const;
  void _internal_set_end_time(int64_t value);
  public:

  // int32 limit = 6;
  void clear_limit();
  int32_t limit() const;
  void set_limit(int32_t value);
  private:
  int32_t _internal_limit() const;
  void _internal_set_limit(int32_t value);
  public:

  // int32 offset = 7;
  void clear_offset();
  int32_t offset() const;
  void set_offset(int32_t value);
  private:
  int32_t _internal_offset() const;
  void _internal_set_offset(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg_log.QueryLogReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int type_;
  int32_t server_id_;
  uint64_t role_id_;
  int64_t start_time_;
  int64_t end_time_;
  int32_t limit_;
  int32_t offset_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5flog_2eproto;
};
// -------------------------------------------------------------------

class QueryLogAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg_log.QueryLogAck) */ {
 public:
  inline QueryLogAck() : QueryLogAck(nullptr) {}
  ~QueryLogAck() override;
  explicit constexpr QueryLogAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QueryLogAck(const QueryLogAck& from);
  QueryLogAck(QueryLogAck&& from) noexcept
    : QueryLogAck() {
    *this = ::std::move(from);
  }

  inline QueryLogAck& operator=(const QueryLogAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryLogAck& operator=(QueryLogAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryLogAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryLogAck* internal_default_instance() {
    return reinterpret_cast<const QueryLogAck*>(
               &_QueryLogAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(QueryLogAck& a, QueryLogAck& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryLogAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryLogAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryLogAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QueryLogAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QueryLogAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const QueryLogAck& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryLogAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg_log.QueryLogAck";
  }
  protected:
  explicit QueryLogAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecordsFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // repeated .msg_log.LogRecord records = 2;
  int records_size() const;
  private:
  int _internal_records_size() const;
  public:
  void clear_records();
  ::msg_log::LogRecord* mutable_records(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord >*
      mutable_records();
  private:
  const ::msg_log::LogRecord& _internal_records(int index) const;
  ::msg_log::LogRecord* _internal_add_records();
  public:
  const ::msg_log::LogRecord& records(int index) const;
  ::msg_log::LogRecord* add_records();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord >&
      records() const;

  // int32 result = 1;
  void clear_result();
  int32_t result() const;
  void set_result(int32_t value);
  private:
  int32_t _internal_result() const;
  void _internal_set_result(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg_log.QueryLogAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord > records_;
  int32_t result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5flog_2eproto;
};
// -------------------------------------------------------------------

class CountLogReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg_log.CountLogReq) */ {
 public:
  inline CountLogReq() : CountLogReq(nullptr) {}
  ~CountLogReq() override;
  explicit constexpr CountLogReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CountLogReq(const CountLogReq& from);
  CountLogReq(CountLogReq&& from) noexcept
    : CountLogReq() {
    *this = ::std::move(from);
  }

  inline CountLogReq& operator=(const CountLogReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CountLogReq& operator=(CountLogReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CountLogReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const CountLogReq* internal_default_instance() {
    return reinterpret_cast<const CountLogReq*>(
               &_CountLogReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(CountLogReq& a, CountLogReq& b) {
    a.Swap(&b);
  }
  inline void Swap(CountLogReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CountLogReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CountLogReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CountLogReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CountLogReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CountLogReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CountLogReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg_log.CountLogReq";
  }
  protected:
  explicit CountLogReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kServerIdFieldNumber = 2,
    kRoleIdFieldNumber = 3,
    kStartTimeFieldNumber = 4,
    kEndTimeFieldNumber = 5,
  };
  // .msg_log.LogType type = 1;
  void clear_type();
  ::msg_log::LogType type() const;
  void set_type(::msg_log::LogType value);
  private:
  ::msg_log::LogType _internal_type() const;
  void _internal_set_type(::msg_log::LogType value);
  public:

  // int32 server_id = 2;
  void clear_server_id();
  int32_t server_id() const;
  void set_server_id(int32_t value);
  private:
  int32_t _internal_server_id() const;
  void _internal_set_server_id(int32_t value);
  public:

  // uint64 role_id = 3;
  void clear_role_id();
  uint64_t role_id() const;
  void set_role_id(uint64_t value);
  private:
  uint64_t _internal_role_id() const;
  void _internal_set_role_id(uint64_t value);
  public:

  // int64 start_time = 4;
  void clear_start_time();
  int64_t start_time() const;
  void set_start_time(int64_t value);
  private:
  int64_t _internal_start_time() const;
  void _internal_set_start_time(int64_t value);
  public:

  // int64 end_time = 5;
  void clear_end_time();
  int64_t end_time() const;
  void set_end_time(int64_t value);
  private:
  int64_t _internal_end_time() const;
  void _internal_set_end_time(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg_log.CountLogReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int type_;
  int32_t server_id_;
  uint64_t role_id_;
  int64_t start_time_;
  int64_t end_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5flog_2eproto;
};
// -------------------------------------------------------------------

class CountLogAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg_log.CountLogAck) */ {
 public:
  inline CountLogAck() : CountLogAck(nullptr) {}
  ~CountLogAck() override;
  explicit constexpr CountLogAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CountLogAck(const CountLogAck& from);
  CountLogAck(CountLogAck&& from) noexcept
    : CountLogAck() {
    *this = ::std::move(from);
  }

  inline CountLogAck& operator=(const CountLogAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline CountLogAck& operator=(CountLogAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CountLogAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const CountLogAck* internal_default_instance() {
    return reinterpret_cast<const CountLogAck*>(
               &_CountLogAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(CountLogAck& a, CountLogAck& b) {
    a.Swap(&b);
  }
  inline void Swap(CountLogAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CountLogAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CountLogAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CountLogAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CountLogAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CountLogAck& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CountLogAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg_log.CountLogAck";
  }
  protected:
  explicit CountLogAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCountFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // int64 count = 2;
  void clear_count();
  int64_t count() const;
  void set_count(int64_t value);
  private:
  int64_t _internal_count() const;
  void _internal_set_count(int64_t value);
  public:

  // int32 result = 1;
  void clear_result();
  int32_t result() const;
  void set_result(int32_t value);
  private:
  int32_t _internal_result() const;
  void _internal_set_result(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg_log.CountLogAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int64_t count_;
  int32_t result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5flog_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogRecord

// int64 log_id = 1;
inline void LogRecord::clear_log_id() {
  log_id_ = int64_t{0};
}
inline int64_t LogRecord::_internal_log_id() const {
  return log_id_;
}
inline int64_t LogRecord::log_id() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.log_id)
  return _internal_log_id();
}
inline void LogRecord::_internal_set_log_id(int64_t value) {
  
  log_id_ = value;
}
inline void LogRecord::set_log_id(int64_t value) {
  _internal_set_log_id(value);
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.log_id)
}

// .msg_log.LogType type = 2;
inline void LogRecord::clear_type() {
  type_ = 0;
}
inline ::msg_log::LogType LogRecord::_internal_type() const {
  return static_cast< ::msg_log::LogType >(type_);
}
inline ::msg_log::LogType LogRecord::type() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.type)
  return _internal_type();
}
inline void LogRecord::_internal_set_type(::msg_log::LogType value) {
  
  type_ = value;
}
inline void LogRecord::set_type(::msg_log::LogType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.type)
}

// .msg_log.LogLevel level = 3;
inline void LogRecord::clear_level() {
  level_ = 0;
}
inline ::msg_log::LogLevel LogRecord::_internal_level() const {
  return static_cast< ::msg_log::LogLevel >(level_);
}
inline ::msg_log::LogLevel LogRecord::level() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.level)
  return _internal_level();
}
inline void LogRecord::_internal_set_level(::msg_log::LogLevel value) {
  
  level_ = value;
}
inline void LogRecord::set_level(::msg_log::LogLevel value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.level)
}

// int32 server_id = 4;
inline void LogRecord::clear_server_id() {
  server_id_ = 0;
}
inline int32_t LogRecord::_internal_server_id() const {
  return server_id_;
}
inline int32_t LogRecord::server_id() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.server_id)
  return _internal_server_id();
}
inline void LogRecord::_internal_set_server_id(int32_t value) {
  
  server_id_ = value;
}
inline void LogRecord::set_server_id(int32_t value) {
  _internal_set_server_id(value);
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.server_id)
}

// uint64 role_id = 5;
inline void LogRecord::clear_role_id() {
  role_id_ = uint64_t{0u};
}
inline uint64_t LogRecord::_internal_role_id() const {
  return role_id_;
}
inline uint64_t LogRecord::role_id() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.role_id)
  return _internal_role_id();
}
inline void LogRecord::_internal_set_role_id(uint64_t value) {
  
  role_id_ = value;
}
inline void LogRecord::set_role_id(uint64_t value) {
  _internal_set_role_id(value);
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.role_id)
}

// string role_name = 6;
inline void LogRecord::clear_role_name() {
  role_name_.ClearToEmpty();
}
inline const std::string& LogRecord::role_name() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.role_name)
  return _internal_role_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogRecord::set_role_name(ArgT0&& arg0, ArgT... args) {
 
 role_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.role_name)
}
inline std::string* LogRecord::mutable_role_name() {
  std::string* _s = _internal_mutable_role_name();
  // @@protoc_insertion_point(field_mutable:msg_log.LogRecord.role_name)
  return _s;
}
inline const std::string& LogRecord::_internal_role_name() const {
  return role_name_.Get();
}
inline void LogRecord::_internal_set_role_name(const std::string& value) {
  
  role_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LogRecord::_internal_mutable_role_name() {
  
  return role_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LogRecord::release_role_name() {
  // @@protoc_insertion_point(field_release:msg_log.LogRecord.role_name)
  return role_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LogRecord::set_allocated_role_name(std::string* role_name) {
  if (role_name != nullptr) {
    
  } else {
    
  }
  role_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), role_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (role_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    role_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg_log.LogRecord.role_name)
}

// string content = 7;
inline void LogRecord::clear_content() {
  content_.ClearToEmpty();
}
inline const std::string& LogRecord::content() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogRecord::set_content(ArgT0&& arg0, ArgT... args) {
 
 content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.content)
}
inline std::string* LogRecord::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:msg_log.LogRecord.content)
  return _s;
}
inline const std::string& LogRecord::_internal_content() const {
  return content_.Get();
}
inline void LogRecord::_internal_set_content(const std::string& value) {
  
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LogRecord::_internal_mutable_content() {
  
  return content_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LogRecord::release_content() {
  // @@protoc_insertion_point(field_release:msg_log.LogRecord.content)
  return content_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LogRecord::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (content_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    content_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg_log.LogRecord.content)
}

// string extra_data = 8;
inline void LogRecord::clear_extra_data() {
  extra_data_.ClearToEmpty();
}
inline const std::string& LogRecord::extra_data() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.extra_data)
  return _internal_extra_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogRecord::set_extra_data(ArgT0&& arg0, ArgT... args) {
 
 extra_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.extra_data)
}
inline std::string* LogRecord::mutable_extra_data() {
  std::string* _s = _internal_mutable_extra_data();
  // @@protoc_insertion_point(field_mutable:msg_log.LogRecord.extra_data)
  return _s;
}
inline const std::string& LogRecord::_internal_extra_data() const {
  return extra_data_.Get();
}
inline void LogRecord::_internal_set_extra_data(const std::string& value) {
  
  extra_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LogRecord::_internal_mutable_extra_data() {
  
  return extra_data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LogRecord::release_extra_data() {
  // @@protoc_insertion_point(field_release:msg_log.LogRecord.extra_data)
  return extra_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LogRecord::set_allocated_extra_data(std::string* extra_data) {
  if (extra_data != nullptr) {
    
  } else {
    
  }
  extra_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), extra_data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (extra_data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    extra_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg_log.LogRecord.extra_data)
}

// int64 log_time = 9;
inline void LogRecord::clear_log_time() {
  log_time_ = int64_t{0};
}
inline int64_t LogRecord::_internal_log_time() const {
  return log_time_;
}
inline int64_t LogRecord::log_time() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.log_time)
  return _internal_log_time();
}
inline void LogRecord::_internal_set_log_time(int64_t value) {
  
  log_time_ = value;
}
inline void LogRecord::set_log_time(int64_t value) {
  _internal_set_log_time(value);
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.log_time)
}

// string ip = 10;
inline void LogRecord::clear_ip() {
  ip_.ClearToEmpty();
}
inline const std::string& LogRecord::ip() const {
  // @@protoc_insertion_point(field_get:msg_log.LogRecord.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogRecord::set_ip(ArgT0&& arg0, ArgT... args) {
 
 ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg_log.LogRecord.ip)
}
inline std::string* LogRecord::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:msg_log.LogRecord.ip)
  return _s;
}
inline const std::string& LogRecord::_internal_ip() const {
  return ip_.Get();
}
inline void LogRecord::_internal_set_ip(const std::string& value) {
  
  ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* LogRecord::_internal_mutable_ip() {
  
  return ip_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* LogRecord::release_ip() {
  // @@protoc_insertion_point(field_release:msg_log.LogRecord.ip)
  return ip_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void LogRecord::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  ip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ip_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg_log.LogRecord.ip)
}

// -------------------------------------------------------------------

// SendLogReq

// .msg_log.LogRecord record = 1;
inline bool SendLogReq::_internal_has_record() const {
  return this != internal_default_instance() && record_ != nullptr;
}
inline bool SendLogReq::has_record() const {
  return _internal_has_record();
}
inline void SendLogReq::clear_record() {
  if (GetArenaForAllocation() == nullptr && record_ != nullptr) {
    delete record_;
  }
  record_ = nullptr;
}
inline const ::msg_log::LogRecord& SendLogReq::_internal_record() const {
  const ::msg_log::LogRecord* p = record_;
  return p != nullptr ? *p : reinterpret_cast<const ::msg_log::LogRecord&>(
      ::msg_log::_LogRecord_default_instance_);
}
inline const ::msg_log::LogRecord& SendLogReq::record() const {
  // @@protoc_insertion_point(field_get:msg_log.SendLogReq.record)
  return _internal_record();
}
inline void SendLogReq::unsafe_arena_set_allocated_record(
    ::msg_log::LogRecord* record) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(record_);
  }
  record_ = record;
  if (record) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg_log.SendLogReq.record)
}
inline ::msg_log::LogRecord* SendLogReq::release_record() {
  
  ::msg_log::LogRecord* temp = record_;
  record_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::msg_log::LogRecord* SendLogReq::unsafe_arena_release_record() {
  // @@protoc_insertion_point(field_release:msg_log.SendLogReq.record)
  
  ::msg_log::LogRecord* temp = record_;
  record_ = nullptr;
  return temp;
}
inline ::msg_log::LogRecord* SendLogReq::_internal_mutable_record() {
  
  if (record_ == nullptr) {
    auto* p = CreateMaybeMessage<::msg_log::LogRecord>(GetArenaForAllocation());
    record_ = p;
  }
  return record_;
}
inline ::msg_log::LogRecord* SendLogReq::mutable_record() {
  ::msg_log::LogRecord* _msg = _internal_mutable_record();
  // @@protoc_insertion_point(field_mutable:msg_log.SendLogReq.record)
  return _msg;
}
inline void SendLogReq::set_allocated_record(::msg_log::LogRecord* record) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete record_;
  }
  if (record) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::msg_log::LogRecord>::GetOwningArena(record);
    if (message_arena != submessage_arena) {
      record = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, record, submessage_arena);
    }
    
  } else {
    
  }
  record_ = record;
  // @@protoc_insertion_point(field_set_allocated:msg_log.SendLogReq.record)
}

// -------------------------------------------------------------------

// SendLogAck

// int32 result = 1;
inline void SendLogAck::clear_result() {
  result_ = 0;
}
inline int32_t SendLogAck::_internal_result() const {
  return result_;
}
inline int32_t SendLogAck::result() const {
  // @@protoc_insertion_point(field_get:msg_log.SendLogAck.result)
  return _internal_result();
}
inline void SendLogAck::_internal_set_result(int32_t value) {
  
  result_ = value;
}
inline void SendLogAck::set_result(int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:msg_log.SendLogAck.result)
}

// int64 log_id = 2;
inline void SendLogAck::clear_log_id() {
  log_id_ = int64_t{0};
}
inline int64_t SendLogAck::_internal_log_id() const {
  return log_id_;
}
inline int64_t SendLogAck::log_id() const {
  // @@protoc_insertion_point(field_get:msg_log.SendLogAck.log_id)
  return _internal_log_id();
}
inline void SendLogAck::_internal_set_log_id(int64_t value) {
  
  log_id_ = value;
}
inline void SendLogAck::set_log_id(int64_t value) {
  _internal_set_log_id(value);
  // @@protoc_insertion_point(field_set:msg_log.SendLogAck.log_id)
}

// -------------------------------------------------------------------

// SendLogBatchReq

// repeated .msg_log.LogRecord records = 1;
inline int SendLogBatchReq::_internal_records_size() const {
  return records_.size();
}
inline int SendLogBatchReq::records_size() const {
  return _internal_records_size();
}
inline void SendLogBatchReq::clear_records() {
  records_.Clear();
}
inline ::msg_log::LogRecord* SendLogBatchReq::mutable_records(int index) {
  // @@protoc_insertion_point(field_mutable:msg_log.SendLogBatchReq.records)
  return records_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord >*
SendLogBatchReq::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:msg_log.SendLogBatchReq.records)
  return &records_;
}
inline const ::msg_log::LogRecord& SendLogBatchReq::_internal_records(int index) const {
  return records_.Get(index);
}
inline const ::msg_log::LogRecord& SendLogBatchReq::records(int index) const {
  // @@protoc_insertion_point(field_get:msg_log.SendLogBatchReq.records)
  return _internal_records(index);
}
inline ::msg_log::LogRecord* SendLogBatchReq::_internal_add_records() {
  return records_.Add();
}
inline ::msg_log::LogRecord* SendLogBatchReq::add_records() {
  ::msg_log::LogRecord* _add = _internal_add_records();
  // @@protoc_insertion_point(field_add:msg_log.SendLogBatchReq.records)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord >&
SendLogBatchReq::records() const {
  // @@protoc_insertion_point(field_list:msg_log.SendLogBatchReq.records)
  return records_;
}

// -------------------------------------------------------------------

// SendLogBatchAck

// int32 result = 1;
inline void SendLogBatchAck::clear_result() {
  result_ = 0;
}
inline int32_t SendLogBatchAck::_internal_result() const {
  return result_;
}
inline int32_t SendLogBatchAck::result() const {
  // @@protoc_insertion_point(field_get:msg_log.SendLogBatchAck.result)
  return _internal_result();
}
inline void SendLogBatchAck::_internal_set_result(int32_t value) {
  
  result_ = value;
}
inline void SendLogBatchAck::set_result(int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:msg_log.SendLogBatchAck.result)
}

// int32 success_count = 2;
inline void SendLogBatchAck::clear_success_count() {
  success_count_ = 0;
}
inline int32_t SendLogBatchAck::_internal_success_count() const {
  return success_count_;
}
inline int32_t SendLogBatchAck::success_count() const {
  // @@protoc_insertion_point(field_get:msg_log.SendLogBatchAck.success_count)
  return _internal_success_count();
}
inline void SendLogBatchAck::_internal_set_success_count(int32_t value) {
  
  success_count_ = value;
}
inline void SendLogBatchAck::set_success_count(int32_t value) {
  _internal_set_success_count(value);
  // @@protoc_insertion_point(field_set:msg_log.SendLogBatchAck.success_count)
}

// int32 failed_count = 3;
inline void SendLogBatchAck::clear_failed_count() {
  failed_count_ = 0;
}
inline int32_t SendLogBatchAck::_internal_failed_count() const {
  return failed_count_;
}
inline int32_t SendLogBatchAck::failed_count() const {
  // @@protoc_insertion_point(field_get:msg_log.SendLogBatchAck.failed_count)
  return _internal_failed_count();
}
inline void SendLogBatchAck::_internal_set_failed_count(int32_t value) {
  
  failed_count_ = value;
}
inline void SendLogBatchAck::set_failed_count(int32_t value) {
  _internal_set_failed_count(value);
  // @@protoc_insertion_point(field_set:msg_log.SendLogBatchAck.failed_count)
}

// -------------------------------------------------------------------

// QueryLogReq

// .msg_log.LogType type = 1;
inline void QueryLogReq::clear_type() {
  type_ = 0;
}
inline ::msg_log::LogType QueryLogReq::_internal_type() const {
  return static_cast< ::msg_log::LogType >(type_);
}
inline ::msg_log::LogType QueryLogReq::type() const {
  // @@protoc_insertion_point(field_get:msg_log.QueryLogReq.type)
  return _internal_type();
}
inline void QueryLogReq::_internal_set_type(::msg_log::LogType value) {
  
  type_ = value;
}
inline void QueryLogReq::set_type(::msg_log::LogType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:msg_log.QueryLogReq.type)
}

// int32 server_id = 2;
inline void QueryLogReq::clear_server_id() {
  server_id_ = 0;
}
inline int32_t QueryLogReq::_internal_server_id() const {
  return server_id_;
}
inline int32_t QueryLogReq::server_id() const {
  // @@protoc_insertion_point(field_get:msg_log.QueryLogReq.server_id)
  return _internal_server_id();
}
inline void QueryLogReq::_internal_set_server_id(int32_t value) {
  
  server_id_ = value;
}
inline void QueryLogReq::set_server_id(int32_t value) {
  _internal_set_server_id(value);
  // @@protoc_insertion_point(field_set:msg_log.QueryLogReq.server_id)
}

// uint64 role_id = 3;
inline void QueryLogReq::clear_role_id() {
  role_id_ = uint64_t{0u};
}
inline uint64_t QueryLogReq::_internal_role_id() const {
  return role_id_;
}
inline uint64_t QueryLogReq::role_id() const {
  // @@protoc_insertion_point(field_get:msg_log.QueryLogReq.role_id)
  return _internal_role_id();
}
inline void QueryLogReq::_internal_set_role_id(uint64_t value) {
  
  role_id_ = value;
}
inline void QueryLogReq::set_role_id(uint64_t value) {
  _internal_set_role_id(value);
  // @@protoc_insertion_point(field_set:msg_log.QueryLogReq.role_id)
}

// int64 start_time = 4;
inline void QueryLogReq::clear_start_time() {
  start_time_ = int64_t{0};
}
inline int64_t QueryLogReq::_internal_start_time() const {
  return start_time_;
}
inline int64_t QueryLogReq::start_time() const {
  // @@protoc_insertion_point(field_get:msg_log.QueryLogReq.start_time)
  return _internal_start_time();
}
inline void QueryLogReq::_internal_set_start_time(int64_t value) {
  
  start_time_ = value;
}
inline void QueryLogReq::set_start_time(int64_t value) {
  _internal_set_start_time(value);
  // @@protoc_insertion_point(field_set:msg_log.QueryLogReq.start_time)
}

// int64 end_time = 5;
inline void QueryLogReq::clear_end_time() {
  end_time_ = int64_t{0};
}
inline int64_t QueryLogReq::_internal_end_time() const {
  return end_time_;
}
inline int64_t QueryLogReq::end_time() const {
  // @@protoc_insertion_point(field_get:msg_log.QueryLogReq.end_time)
  return _internal_end_time();
}
inline void QueryLogReq::_internal_set_end_time(int64_t value) {
  
  end_time_ = value;
}
inline void QueryLogReq::set_end_time(int64_t value) {
  _internal_set_end_time(value);
  // @@protoc_insertion_point(field_set:msg_log.QueryLogReq.end_time)
}

// int32 limit = 6;
inline void QueryLogReq::clear_limit() {
  limit_ = 0;
}
inline int32_t QueryLogReq::_internal_limit() const {
  return limit_;
}
inline int32_t QueryLogReq::limit() const {
  // @@protoc_insertion_point(field_get:msg_log.QueryLogReq.limit)
  return _internal_limit();
}
inline void QueryLogReq::_internal_set_limit(int32_t value) {
  
  limit_ = value;
}
inline void QueryLogReq::set_limit(int32_t value) {
  _internal_set_limit(value);
  // @@protoc_insertion_point(field_set:msg_log.QueryLogReq.limit)
}

// int32 offset = 7;
inline void QueryLogReq::clear_offset() {
  offset_ = 0;
}
inline int32_t QueryLogReq::_internal_offset() const {
  return offset_;
}
inline int32_t QueryLogReq::offset() const {
  // @@protoc_insertion_point(field_get:msg_log.QueryLogReq.offset)
  return _internal_offset();
}
inline void QueryLogReq::_internal_set_offset(int32_t value) {
  
  offset_ = value;
}
inline void QueryLogReq::set_offset(int32_t value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:msg_log.QueryLogReq.offset)
}

// -------------------------------------------------------------------

// QueryLogAck

// int32 result = 1;
inline void QueryLogAck::clear_result() {
  result_ = 0;
}
inline int32_t QueryLogAck::_internal_result() const {
  return result_;
}
inline int32_t QueryLogAck::result() const {
  // @@protoc_insertion_point(field_get:msg_log.QueryLogAck.result)
  return _internal_result();
}
inline void QueryLogAck::_internal_set_result(int32_t value) {
  
  result_ = value;
}
inline void QueryLogAck::set_result(int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:msg_log.QueryLogAck.result)
}

// repeated .msg_log.LogRecord records = 2;
inline int QueryLogAck::_internal_records_size() const {
  return records_.size();
}
inline int QueryLogAck::records_size() const {
  return _internal_records_size();
}
inline void QueryLogAck::clear_records() {
  records_.Clear();
}
inline ::msg_log::LogRecord* QueryLogAck::mutable_records(int index) {
  // @@protoc_insertion_point(field_mutable:msg_log.QueryLogAck.records)
  return records_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord >*
QueryLogAck::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:msg_log.QueryLogAck.records)
  return &records_;
}
inline const ::msg_log::LogRecord& QueryLogAck::_internal_records(int index) const {
  return records_.Get(index);
}
inline const ::msg_log::LogRecord& QueryLogAck::records(int index) const {
  // @@protoc_insertion_point(field_get:msg_log.QueryLogAck.records)
  return _internal_records(index);
}
inline ::msg_log::LogRecord* QueryLogAck::_internal_add_records() {
  return records_.Add();
}
inline ::msg_log::LogRecord* QueryLogAck::add_records() {
  ::msg_log::LogRecord* _add = _internal_add_records();
  // @@protoc_insertion_point(field_add:msg_log.QueryLogAck.records)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg_log::LogRecord >&
QueryLogAck::records() const {
  // @@protoc_insertion_point(field_list:msg_log.QueryLogAck.records)
  return records_;
}

// -------------------------------------------------------------------

// CountLogReq

// .msg_log.LogType type = 1;
inline void CountLogReq::clear_type() {
  type_ = 0;
}
inline ::msg_log::LogType CountLogReq::_internal_type() const {
  return static_cast< ::msg_log::LogType >(type_);
}
inline ::msg_log::LogType CountLogReq::type() const {
  // @@protoc_insertion_point(field_get:msg_log.CountLogReq.type)
  return _internal_type();
}
inline void CountLogReq::_internal_set_type(::msg_log::LogType value) {
  
  type_ = value;
}
inline void CountLogReq::set_type(::msg_log::LogType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:msg_log.CountLogReq.type)
}

// int32 server_id = 2;
inline void CountLogReq::clear_server_id() {
  server_id_ = 0;
}
inline int32_t CountLogReq::_internal_server_id() const {
  return server_id_;
}
inline int32_t CountLogReq::server_id() const {
  // @@protoc_insertion_point(field_get:msg_log.CountLogReq.server_id)
  return _internal_server_id();
}
inline void CountLogReq::_internal_set_server_id(int32_t value) {
  
  server_id_ = value;
}
inline void CountLogReq::set_server_id(int32_t value) {
  _internal_set_server_id(value);
  // @@protoc_insertion_point(field_set:msg_log.CountLogReq.server_id)
}

// uint64 role_id = 3;
inline void CountLogReq::clear_role_id() {
  role_id_ = uint64_t{0u};
}
inline uint64_t CountLogReq::_internal_role_id() const {
  return role_id_;
}
inline uint64_t CountLogReq::role_id() const {
  // @@protoc_insertion_point(field_get:msg_log.CountLogReq.role_id)
  return _internal_role_id();
}
inline void CountLogReq::_internal_set_role_id(uint64_t value) {
  
  role_id_ = value;
}
inline void CountLogReq::set_role_id(uint64_t value) {
  _internal_set_role_id(value);
  // @@protoc_insertion_point(field_set:msg_log.CountLogReq.role_id)
}

// int64 start_time = 4;
inline void CountLogReq::clear_start_time() {
  start_time_ = int64_t{0};
}
inline int64_t CountLogReq::_internal_start_time() const {
  return start_time_;
}
inline int64_t CountLogReq::start_time() const {
  // @@protoc_insertion_point(field_get:msg_log.CountLogReq.start_time)
  return _internal_start_time();
}
inline void CountLogReq::_internal_set_start_time(int64_t value) {
  
  start_time_ = value;
}
inline void CountLogReq::set_start_time(int64_t value) {
  _internal_set_start_time(value);
  // @@protoc_insertion_point(field_set:msg_log.CountLogReq.start_time)
}

// int64 end_time = 5;
inline void CountLogReq::clear_end_time() {
  end_time_ = int64_t{0};
}
inline int64_t CountLogReq::_internal_end_time() const {
  return end_time_;
}
inline int64_t CountLogReq::end_time() const {
  // @@protoc_insertion_point(field_get:msg_log.CountLogReq.end_time)
  return _internal_end_time();
}
inline void CountLogReq::_internal_set_end_time(int64_t value) {
  
  end_time_ = value;
}
inline void CountLogReq::set_end_time(int64_t value) {
  _internal_set_end_time(value);
  // @@protoc_insertion_point(field_set:msg_log.CountLogReq.end_time)
}

// -------------------------------------------------------------------

// CountLogAck

// int32 result = 1;
inline void CountLogAck::clear_result() {
  result_ = 0;
}
inline int32_t CountLogAck::_internal_result() const {
  return result_;
}
inline int32_t CountLogAck::result() const {
  // @@protoc_insertion_point(field_get:msg_log.CountLogAck.result)
  return _internal_result();
}
inline void CountLogAck::_internal_set_result(int32_t value) {
  
  result_ = value;
}
inline void CountLogAck::set_result(int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:msg_log.CountLogAck.result)
}

// int64 count = 2;
inline void CountLogAck::clear_count() {
  count_ = int64_t{0};
}
inline int64_t CountLogAck::_internal_count() const {
  return count_;
}
inline int64_t CountLogAck::count() const {
  // @@protoc_insertion_point(field_get:msg_log.CountLogAck.count)
  return _internal_count();
}
inline void CountLogAck::_internal_set_count(int64_t value) {
  
  count_ = value;
}
inline void CountLogAck::set_count(int64_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:msg_log.CountLogAck.count)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msg_log

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::msg_log::LogType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::msg_log::LogType>() {
  return ::msg_log::LogType_descriptor();
}
template <> struct is_proto_enum< ::msg_log::LogLevel> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::msg_log::LogLevel>() {
  return ::msg_log::LogLevel_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_5flog_2eproto
