// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_db.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fdb_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fdb_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_5fdb_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fdb_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5fdb_2eproto;
namespace game_server {
class DBRequest;
struct DBRequestDefaultTypeInternal;
extern DBRequestDefaultTypeInternal _DBRequest_default_instance_;
class DBResponse;
struct DBResponseDefaultTypeInternal;
extern DBResponseDefaultTypeInternal _DBResponse_default_instance_;
class RoleInfo;
struct RoleInfoDefaultTypeInternal;
extern RoleInfoDefaultTypeInternal _RoleInfo_default_instance_;
}  // namespace game_server
PROTOBUF_NAMESPACE_OPEN
template<> ::game_server::DBRequest* Arena::CreateMaybeMessage<::game_server::DBRequest>(Arena*);
template<> ::game_server::DBResponse* Arena::CreateMaybeMessage<::game_server::DBResponse>(Arena*);
template<> ::game_server::RoleInfo* Arena::CreateMaybeMessage<::game_server::RoleInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace game_server {

enum DBOperationType : int {
  DB_OP_CREATE_ACCOUNT = 0,
  DB_OP_VERIFY_ACCOUNT = 1,
  DB_OP_GET_ACCOUNT_INFO = 2,
  DB_OP_SEAL_ACCOUNT = 3,
  DB_OP_UNSEAL_ACCOUNT = 4,
  DB_OP_RECORD_LOGIN_LOG = 5,
  DB_OP_CREATE_ROLE = 6,
  DB_OP_UPDATE_ROLE = 7,
  DB_OP_DELETE_ROLE = 8,
  DB_OP_GET_ROLE_LIST = 9,
  DB_OP_GET_ROLE_DATA = 10,
  DBOperationType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DBOperationType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DBOperationType_IsValid(int value);
constexpr DBOperationType DBOperationType_MIN = DB_OP_CREATE_ACCOUNT;
constexpr DBOperationType DBOperationType_MAX = DB_OP_GET_ROLE_DATA;
constexpr int DBOperationType_ARRAYSIZE = DBOperationType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DBOperationType_descriptor();
template<typename T>
inline const std::string& DBOperationType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DBOperationType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DBOperationType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DBOperationType_descriptor(), enum_t_value);
}
inline bool DBOperationType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DBOperationType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DBOperationType>(
    DBOperationType_descriptor(), name, value);
}
// ===================================================================

class DBRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game_server.DBRequest) */ {
 public:
  inline DBRequest() : DBRequest(nullptr) {}
  ~DBRequest() override;
  explicit constexpr DBRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DBRequest(const DBRequest& from);
  DBRequest(DBRequest&& from) noexcept
    : DBRequest() {
    *this = ::std::move(from);
  }

  inline DBRequest& operator=(const DBRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DBRequest& operator=(DBRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DBRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DBRequest* internal_default_instance() {
    return reinterpret_cast<const DBRequest*>(
               &_DBRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DBRequest& a, DBRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DBRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DBRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DBRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DBRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DBRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DBRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DBRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game_server.DBRequest";
  }
  protected:
  explicit DBRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountNameFieldNumber = 3,
    kPasswordFieldNumber = 4,
    kVersionFieldNumber = 7,
    kUuidFieldNumber = 8,
    kIdfaFieldNumber = 9,
    kImodelFieldNumber = 10,
    kImeiFieldNumber = 11,
    kRoleNameFieldNumber = 14,
    kAccountIdFieldNumber = 2,
    kOpTypeFieldNumber = 1,
    kChannelFieldNumber = 5,
    kSealTimeFieldNumber = 6,
    kIpFieldNumber = 12,
    kRoleIdFieldNumber = 13,
    kServerIdFieldNumber = 15,
    kCareerFieldNumber = 16,
    kExpFieldNumber = 18,
    kLevelFieldNumber = 17,
    kHeadIdFieldNumber = 19,
    kPortraitFrameFieldNumber = 20,
    kIsDeletedFieldNumber = 21,
    kDeleteTimeFieldNumber = 22,
  };
  // string account_name = 3;
  void clear_account_name();
  const std::string& account_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account_name();
  PROTOBUF_NODISCARD std::string* release_account_name();
  void set_allocated_account_name(std::string* account_name);
  private:
  const std::string& _internal_account_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account_name(const std::string& value);
  std::string* _internal_mutable_account_name();
  public:

  // string password = 4;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string version = 7;
  void clear_version();
  const std::string& version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_version();
  PROTOBUF_NODISCARD std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // string uuid = 8;
  void clear_uuid();
  const std::string& uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // string idfa = 9;
  void clear_idfa();
  const std::string& idfa() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_idfa(ArgT0&& arg0, ArgT... args);
  std::string* mutable_idfa();
  PROTOBUF_NODISCARD std::string* release_idfa();
  void set_allocated_idfa(std::string* idfa);
  private:
  const std::string& _internal_idfa() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_idfa(const std::string& value);
  std::string* _internal_mutable_idfa();
  public:

  // string imodel = 10;
  void clear_imodel();
  const std::string& imodel() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_imodel(ArgT0&& arg0, ArgT... args);
  std::string* mutable_imodel();
  PROTOBUF_NODISCARD std::string* release_imodel();
  void set_allocated_imodel(std::string* imodel);
  private:
  const std::string& _internal_imodel() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_imodel(const std::string& value);
  std::string* _internal_mutable_imodel();
  public:

  // string imei = 11;
  void clear_imei();
  const std::string& imei() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_imei(ArgT0&& arg0, ArgT... args);
  std::string* mutable_imei();
  PROTOBUF_NODISCARD std::string* release_imei();
  void set_allocated_imei(std::string* imei);
  private:
  const std::string& _internal_imei() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_imei(const std::string& value);
  std::string* _internal_mutable_imei();
  public:

  // string role_name = 14;
  void clear_role_name();
  const std::string& role_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_role_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_role_name();
  PROTOBUF_NODISCARD std::string* release_role_name();
  void set_allocated_role_name(std::string* role_name);
  private:
  const std::string& _internal_role_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_role_name(const std::string& value);
  std::string* _internal_mutable_role_name();
  public:

  // uint64 account_id = 2;
  void clear_account_id();
  uint64_t account_id() const;
  void set_account_id(uint64_t value);
  private:
  uint64_t _internal_account_id() const;
  void _internal_set_account_id(uint64_t value);
  public:

  // .game_server.DBOperationType op_type = 1;
  void clear_op_type();
  ::game_server::DBOperationType op_type() const;
  void set_op_type(::game_server::DBOperationType value);
  private:
  ::game_server::DBOperationType _internal_op_type() const;
  void _internal_set_op_type(::game_server::DBOperationType value);
  public:

  // int32 channel = 5;
  void clear_channel();
  int32_t channel() const;
  void set_channel(int32_t value);
  private:
  int32_t _internal_channel() const;
  void _internal_set_channel(int32_t value);
  public:

  // int32 seal_time = 6;
  void clear_seal_time();
  int32_t seal_time() const;
  void set_seal_time(int32_t value);
  private:
  int32_t _internal_seal_time() const;
  void _internal_set_seal_time(int32_t value);
  public:

  // int32 ip = 12;
  void clear_ip();
  int32_t ip() const;
  void set_ip(int32_t value);
  private:
  int32_t _internal_ip() const;
  void _internal_set_ip(int32_t value);
  public:

  // uint64 role_id = 13;
  void clear_role_id();
  uint64_t role_id() const;
  void set_role_id(uint64_t value);
  private:
  uint64_t _internal_role_id() const;
  void _internal_set_role_id(uint64_t value);
  public:

  // int32 server_id = 15;
  void clear_server_id();
  int32_t server_id() const;
  void set_server_id(int32_t value);
  private:
  int32_t _internal_server_id() const;
  void _internal_set_server_id(int32_t value);
  public:

  // int32 career = 16;
  void clear_career();
  int32_t career() const;
  void set_career(int32_t value);
  private:
  int32_t _internal_career() const;
  void _internal_set_career(int32_t value);
  public:

  // int64 exp = 18;
  void clear_exp();
  int64_t exp() const;
  void set_exp(int64_t value);
  private:
  int64_t _internal_exp() const;
  void _internal_set_exp(int64_t value);
  public:

  // int32 level = 17;
  void clear_level();
  int32_t level() const;
  void set_level(int32_t value);
  private:
  int32_t _internal_level() const;
  void _internal_set_level(int32_t value);
  public:

  // int32 head_id = 19;
  void clear_head_id();
  int32_t head_id() const;
  void set_head_id(int32_t value);
  private:
  int32_t _internal_head_id() const;
  void _internal_set_head_id(int32_t value);
  public:

  // int32 portrait_frame = 20;
  void clear_portrait_frame();
  int32_t portrait_frame() const;
  void set_portrait_frame(int32_t value);
  private:
  int32_t _internal_portrait_frame() const;
  void _internal_set_portrait_frame(int32_t value);
  public:

  // int32 is_deleted = 21;
  void clear_is_deleted();
  int32_t is_deleted() const;
  void set_is_deleted(int32_t value);
  private:
  int32_t _internal_is_deleted() const;
  void _internal_set_is_deleted(int32_t value);
  public:

  // int64 delete_time = 22;
  void clear_delete_time();
  int64_t delete_time() const;
  void set_delete_time(int64_t value);
  private:
  int64_t _internal_delete_time() const;
  void _internal_set_delete_time(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:game_server.DBRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr idfa_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr imodel_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr imei_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr role_name_;
  uint64_t account_id_;
  int op_type_;
  int32_t channel_;
  int32_t seal_time_;
  int32_t ip_;
  uint64_t role_id_;
  int32_t server_id_;
  int32_t career_;
  int64_t exp_;
  int32_t level_;
  int32_t head_id_;
  int32_t portrait_frame_;
  int32_t is_deleted_;
  int64_t delete_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5fdb_2eproto;
};
// -------------------------------------------------------------------

class DBResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game_server.DBResponse) */ {
 public:
  inline DBResponse() : DBResponse(nullptr) {}
  ~DBResponse() override;
  explicit constexpr DBResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DBResponse(const DBResponse& from);
  DBResponse(DBResponse&& from) noexcept
    : DBResponse() {
    *this = ::std::move(from);
  }

  inline DBResponse& operator=(const DBResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DBResponse& operator=(DBResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DBResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const DBResponse* internal_default_instance() {
    return reinterpret_cast<const DBResponse*>(
               &_DBResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DBResponse& a, DBResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DBResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DBResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DBResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DBResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DBResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DBResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DBResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game_server.DBResponse";
  }
  protected:
  explicit DBResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoleListFieldNumber = 12,
    kRetMsgFieldNumber = 2,
    kAccountNameFieldNumber = 4,
    kRoleInfoFieldNumber = 13,
    kAccountIdFieldNumber = 3,
    kRetCodeFieldNumber = 1,
    kChannelFieldNumber = 5,
    kCreateTimeFieldNumber = 6,
    kLastLoginTimeFieldNumber = 7,
    kLastLoginIpFieldNumber = 8,
    kIsSealedFieldNumber = 9,
    kReviewFieldNumber = 11,
    kSealEndTimeFieldNumber = 10,
  };
  // repeated .game_server.RoleInfo role_list = 12;
  int role_list_size() const;
  private:
  int _internal_role_list_size() const;
  public:
  void clear_role_list();
  ::game_server::RoleInfo* mutable_role_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game_server::RoleInfo >*
      mutable_role_list();
  private:
  const ::game_server::RoleInfo& _internal_role_list(int index) const;
  ::game_server::RoleInfo* _internal_add_role_list();
  public:
  const ::game_server::RoleInfo& role_list(int index) const;
  ::game_server::RoleInfo* add_role_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game_server::RoleInfo >&
      role_list() const;

  // string ret_msg = 2;
  void clear_ret_msg();
  const std::string& ret_msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ret_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ret_msg();
  PROTOBUF_NODISCARD std::string* release_ret_msg();
  void set_allocated_ret_msg(std::string* ret_msg);
  private:
  const std::string& _internal_ret_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ret_msg(const std::string& value);
  std::string* _internal_mutable_ret_msg();
  public:

  // string account_name = 4;
  void clear_account_name();
  const std::string& account_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account_name();
  PROTOBUF_NODISCARD std::string* release_account_name();
  void set_allocated_account_name(std::string* account_name);
  private:
  const std::string& _internal_account_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account_name(const std::string& value);
  std::string* _internal_mutable_account_name();
  public:

  // .game_server.RoleInfo role_info = 13;
  bool has_role_info() const;
  private:
  bool _internal_has_role_info() const;
  public:
  void clear_role_info();
  const ::game_server::RoleInfo& role_info() const;
  PROTOBUF_NODISCARD ::game_server::RoleInfo* release_role_info();
  ::game_server::RoleInfo* mutable_role_info();
  void set_allocated_role_info(::game_server::RoleInfo* role_info);
  private:
  const ::game_server::RoleInfo& _internal_role_info() const;
  ::game_server::RoleInfo* _internal_mutable_role_info();
  public:
  void unsafe_arena_set_allocated_role_info(
      ::game_server::RoleInfo* role_info);
  ::game_server::RoleInfo* unsafe_arena_release_role_info();

  // uint64 account_id = 3;
  void clear_account_id();
  uint64_t account_id() const;
  void set_account_id(uint64_t value);
  private:
  uint64_t _internal_account_id() const;
  void _internal_set_account_id(uint64_t value);
  public:

  // int32 ret_code = 1;
  void clear_ret_code();
  int32_t ret_code() const;
  void set_ret_code(int32_t value);
  private:
  int32_t _internal_ret_code() const;
  void _internal_set_ret_code(int32_t value);
  public:

  // int32 channel = 5;
  void clear_channel();
  int32_t channel() const;
  void set_channel(int32_t value);
  private:
  int32_t _internal_channel() const;
  void _internal_set_channel(int32_t value);
  public:

  // int64 create_time = 6;
  void clear_create_time();
  int64_t create_time() const;
  void set_create_time(int64_t value);
  private:
  int64_t _internal_create_time() const;
  void _internal_set_create_time(int64_t value);
  public:

  // int64 last_login_time = 7;
  void clear_last_login_time();
  int64_t last_login_time() const;
  void set_last_login_time(int64_t value);
  private:
  int64_t _internal_last_login_time() const;
  void _internal_set_last_login_time(int64_t value);
  public:

  // int32 last_login_ip = 8;
  void clear_last_login_ip();
  int32_t last_login_ip() const;
  void set_last_login_ip(int32_t value);
  private:
  int32_t _internal_last_login_ip() const;
  void _internal_set_last_login_ip(int32_t value);
  public:

  // bool is_sealed = 9;
  void clear_is_sealed();
  bool is_sealed() const;
  void set_is_sealed(bool value);
  private:
  bool _internal_is_sealed() const;
  void _internal_set_is_sealed(bool value);
  public:

  // bool review = 11;
  void clear_review();
  bool review() const;
  void set_review(bool value);
  private:
  bool _internal_review() const;
  void _internal_set_review(bool value);
  public:

  // int64 seal_end_time = 10;
  void clear_seal_end_time();
  int64_t seal_end_time() const;
  void set_seal_end_time(int64_t value);
  private:
  int64_t _internal_seal_end_time() const;
  void _internal_set_seal_end_time(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:game_server.DBResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game_server::RoleInfo > role_list_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ret_msg_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_name_;
  ::game_server::RoleInfo* role_info_;
  uint64_t account_id_;
  int32_t ret_code_;
  int32_t channel_;
  int64_t create_time_;
  int64_t last_login_time_;
  int32_t last_login_ip_;
  bool is_sealed_;
  bool review_;
  int64_t seal_end_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5fdb_2eproto;
};
// -------------------------------------------------------------------

class RoleInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game_server.RoleInfo) */ {
 public:
  inline RoleInfo() : RoleInfo(nullptr) {}
  ~RoleInfo() override;
  explicit constexpr RoleInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleInfo(const RoleInfo& from);
  RoleInfo(RoleInfo&& from) noexcept
    : RoleInfo() {
    *this = ::std::move(from);
  }

  inline RoleInfo& operator=(const RoleInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleInfo& operator=(RoleInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleInfo* internal_default_instance() {
    return reinterpret_cast<const RoleInfo*>(
               &_RoleInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RoleInfo& a, RoleInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RoleInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game_server.RoleInfo";
  }
  protected:
  explicit RoleInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoleNameFieldNumber = 4,
    kRoleIdFieldNumber = 1,
    kAccountIdFieldNumber = 2,
    kServerIdFieldNumber = 3,
    kCareerFieldNumber = 5,
    kExpFieldNumber = 7,
    kLevelFieldNumber = 6,
    kHeadIdFieldNumber = 8,
    kCreateTimeFieldNumber = 10,
    kPortraitFrameFieldNumber = 9,
    kIsDeletedFieldNumber = 12,
    kLastLoginTimeFieldNumber = 11,
    kDeleteTimeFieldNumber = 13,
  };
  // string role_name = 4;
  void clear_role_name();
  const std::string& role_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_role_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_role_name();
  PROTOBUF_NODISCARD std::string* release_role_name();
  void set_allocated_role_name(std::string* role_name);
  private:
  const std::string& _internal_role_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_role_name(const std::string& value);
  std::string* _internal_mutable_role_name();
  public:

  // uint64 role_id = 1;
  void clear_role_id();
  uint64_t role_id() const;
  void set_role_id(uint64_t value);
  private:
  uint64_t _internal_role_id() const;
  void _internal_set_role_id(uint64_t value);
  public:

  // uint64 account_id = 2;
  void clear_account_id();
  uint64_t account_id() const;
  void set_account_id(uint64_t value);
  private:
  uint64_t _internal_account_id() const;
  void _internal_set_account_id(uint64_t value);
  public:

  // int32 server_id = 3;
  void clear_server_id();
  int32_t server_id() const;
  void set_server_id(int32_t value);
  private:
  int32_t _internal_server_id() const;
  void _internal_set_server_id(int32_t value);
  public:

  // int32 career = 5;
  void clear_career();
  int32_t career() const;
  void set_career(int32_t value);
  private:
  int32_t _internal_career() const;
  void _internal_set_career(int32_t value);
  public:

  // int64 exp = 7;
  void clear_exp();
  int64_t exp() const;
  void set_exp(int64_t value);
  private:
  int64_t _internal_exp() const;
  void _internal_set_exp(int64_t value);
  public:

  // int32 level = 6;
  void clear_level();
  int32_t level() const;
  void set_level(int32_t value);
  private:
  int32_t _internal_level() const;
  void _internal_set_level(int32_t value);
  public:

  // int32 head_id = 8;
  void clear_head_id();
  int32_t head_id() const;
  void set_head_id(int32_t value);
  private:
  int32_t _internal_head_id() const;
  void _internal_set_head_id(int32_t value);
  public:

  // int64 create_time = 10;
  void clear_create_time();
  int64_t create_time() const;
  void set_create_time(int64_t value);
  private:
  int64_t _internal_create_time() const;
  void _internal_set_create_time(int64_t value);
  public:

  // int32 portrait_frame = 9;
  void clear_portrait_frame();
  int32_t portrait_frame() const;
  void set_portrait_frame(int32_t value);
  private:
  int32_t _internal_portrait_frame() const;
  void _internal_set_portrait_frame(int32_t value);
  public:

  // int32 is_deleted = 12;
  void clear_is_deleted();
  int32_t is_deleted() const;
  void set_is_deleted(int32_t value);
  private:
  int32_t _internal_is_deleted() const;
  void _internal_set_is_deleted(int32_t value);
  public:

  // int64 last_login_time = 11;
  void clear_last_login_time();
  int64_t last_login_time() const;
  void set_last_login_time(int64_t value);
  private:
  int64_t _internal_last_login_time() const;
  void _internal_set_last_login_time(int64_t value);
  public:

  // int64 delete_time = 13;
  void clear_delete_time();
  int64_t delete_time() const;
  void set_delete_time(int64_t value);
  private:
  int64_t _internal_delete_time() const;
  void _internal_set_delete_time(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:game_server.RoleInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr role_name_;
  uint64_t role_id_;
  uint64_t account_id_;
  int32_t server_id_;
  int32_t career_;
  int64_t exp_;
  int32_t level_;
  int32_t head_id_;
  int64_t create_time_;
  int32_t portrait_frame_;
  int32_t is_deleted_;
  int64_t last_login_time_;
  int64_t delete_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5fdb_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DBRequest

// .game_server.DBOperationType op_type = 1;
inline void DBRequest::clear_op_type() {
  op_type_ = 0;
}
inline ::game_server::DBOperationType DBRequest::_internal_op_type() const {
  return static_cast< ::game_server::DBOperationType >(op_type_);
}
inline ::game_server::DBOperationType DBRequest::op_type() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.op_type)
  return _internal_op_type();
}
inline void DBRequest::_internal_set_op_type(::game_server::DBOperationType value) {
  
  op_type_ = value;
}
inline void DBRequest::set_op_type(::game_server::DBOperationType value) {
  _internal_set_op_type(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.op_type)
}

// uint64 account_id = 2;
inline void DBRequest::clear_account_id() {
  account_id_ = uint64_t{0u};
}
inline uint64_t DBRequest::_internal_account_id() const {
  return account_id_;
}
inline uint64_t DBRequest::account_id() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.account_id)
  return _internal_account_id();
}
inline void DBRequest::_internal_set_account_id(uint64_t value) {
  
  account_id_ = value;
}
inline void DBRequest::set_account_id(uint64_t value) {
  _internal_set_account_id(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.account_id)
}

// string account_name = 3;
inline void DBRequest::clear_account_name() {
  account_name_.ClearToEmpty();
}
inline const std::string& DBRequest::account_name() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.account_name)
  return _internal_account_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBRequest::set_account_name(ArgT0&& arg0, ArgT... args) {
 
 account_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBRequest.account_name)
}
inline std::string* DBRequest::mutable_account_name() {
  std::string* _s = _internal_mutable_account_name();
  // @@protoc_insertion_point(field_mutable:game_server.DBRequest.account_name)
  return _s;
}
inline const std::string& DBRequest::_internal_account_name() const {
  return account_name_.Get();
}
inline void DBRequest::_internal_set_account_name(const std::string& value) {
  
  account_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBRequest::_internal_mutable_account_name() {
  
  return account_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBRequest::release_account_name() {
  // @@protoc_insertion_point(field_release:game_server.DBRequest.account_name)
  return account_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBRequest::set_allocated_account_name(std::string* account_name) {
  if (account_name != nullptr) {
    
  } else {
    
  }
  account_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), account_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (account_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    account_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBRequest.account_name)
}

// string password = 4;
inline void DBRequest::clear_password() {
  password_.ClearToEmpty();
}
inline const std::string& DBRequest::password() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBRequest::set_password(ArgT0&& arg0, ArgT... args) {
 
 password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBRequest.password)
}
inline std::string* DBRequest::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:game_server.DBRequest.password)
  return _s;
}
inline const std::string& DBRequest::_internal_password() const {
  return password_.Get();
}
inline void DBRequest::_internal_set_password(const std::string& value) {
  
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBRequest::_internal_mutable_password() {
  
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBRequest::release_password() {
  // @@protoc_insertion_point(field_release:game_server.DBRequest.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBRequest::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBRequest.password)
}

// int32 channel = 5;
inline void DBRequest::clear_channel() {
  channel_ = 0;
}
inline int32_t DBRequest::_internal_channel() const {
  return channel_;
}
inline int32_t DBRequest::channel() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.channel)
  return _internal_channel();
}
inline void DBRequest::_internal_set_channel(int32_t value) {
  
  channel_ = value;
}
inline void DBRequest::set_channel(int32_t value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.channel)
}

// int32 seal_time = 6;
inline void DBRequest::clear_seal_time() {
  seal_time_ = 0;
}
inline int32_t DBRequest::_internal_seal_time() const {
  return seal_time_;
}
inline int32_t DBRequest::seal_time() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.seal_time)
  return _internal_seal_time();
}
inline void DBRequest::_internal_set_seal_time(int32_t value) {
  
  seal_time_ = value;
}
inline void DBRequest::set_seal_time(int32_t value) {
  _internal_set_seal_time(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.seal_time)
}

// string version = 7;
inline void DBRequest::clear_version() {
  version_.ClearToEmpty();
}
inline const std::string& DBRequest::version() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.version)
  return _internal_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBRequest::set_version(ArgT0&& arg0, ArgT... args) {
 
 version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBRequest.version)
}
inline std::string* DBRequest::mutable_version() {
  std::string* _s = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:game_server.DBRequest.version)
  return _s;
}
inline const std::string& DBRequest::_internal_version() const {
  return version_.Get();
}
inline void DBRequest::_internal_set_version(const std::string& value) {
  
  version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBRequest::_internal_mutable_version() {
  
  return version_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBRequest::release_version() {
  // @@protoc_insertion_point(field_release:game_server.DBRequest.version)
  return version_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBRequest::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  version_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (version_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBRequest.version)
}

// string uuid = 8;
inline void DBRequest::clear_uuid() {
  uuid_.ClearToEmpty();
}
inline const std::string& DBRequest::uuid() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.uuid)
  return _internal_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBRequest::set_uuid(ArgT0&& arg0, ArgT... args) {
 
 uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBRequest.uuid)
}
inline std::string* DBRequest::mutable_uuid() {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:game_server.DBRequest.uuid)
  return _s;
}
inline const std::string& DBRequest::_internal_uuid() const {
  return uuid_.Get();
}
inline void DBRequest::_internal_set_uuid(const std::string& value) {
  
  uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBRequest::_internal_mutable_uuid() {
  
  return uuid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBRequest::release_uuid() {
  // @@protoc_insertion_point(field_release:game_server.DBRequest.uuid)
  return uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBRequest::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uuid,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (uuid_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBRequest.uuid)
}

// string idfa = 9;
inline void DBRequest::clear_idfa() {
  idfa_.ClearToEmpty();
}
inline const std::string& DBRequest::idfa() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.idfa)
  return _internal_idfa();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBRequest::set_idfa(ArgT0&& arg0, ArgT... args) {
 
 idfa_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBRequest.idfa)
}
inline std::string* DBRequest::mutable_idfa() {
  std::string* _s = _internal_mutable_idfa();
  // @@protoc_insertion_point(field_mutable:game_server.DBRequest.idfa)
  return _s;
}
inline const std::string& DBRequest::_internal_idfa() const {
  return idfa_.Get();
}
inline void DBRequest::_internal_set_idfa(const std::string& value) {
  
  idfa_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBRequest::_internal_mutable_idfa() {
  
  return idfa_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBRequest::release_idfa() {
  // @@protoc_insertion_point(field_release:game_server.DBRequest.idfa)
  return idfa_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBRequest::set_allocated_idfa(std::string* idfa) {
  if (idfa != nullptr) {
    
  } else {
    
  }
  idfa_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), idfa,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (idfa_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    idfa_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBRequest.idfa)
}

// string imodel = 10;
inline void DBRequest::clear_imodel() {
  imodel_.ClearToEmpty();
}
inline const std::string& DBRequest::imodel() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.imodel)
  return _internal_imodel();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBRequest::set_imodel(ArgT0&& arg0, ArgT... args) {
 
 imodel_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBRequest.imodel)
}
inline std::string* DBRequest::mutable_imodel() {
  std::string* _s = _internal_mutable_imodel();
  // @@protoc_insertion_point(field_mutable:game_server.DBRequest.imodel)
  return _s;
}
inline const std::string& DBRequest::_internal_imodel() const {
  return imodel_.Get();
}
inline void DBRequest::_internal_set_imodel(const std::string& value) {
  
  imodel_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBRequest::_internal_mutable_imodel() {
  
  return imodel_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBRequest::release_imodel() {
  // @@protoc_insertion_point(field_release:game_server.DBRequest.imodel)
  return imodel_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBRequest::set_allocated_imodel(std::string* imodel) {
  if (imodel != nullptr) {
    
  } else {
    
  }
  imodel_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), imodel,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (imodel_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    imodel_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBRequest.imodel)
}

// string imei = 11;
inline void DBRequest::clear_imei() {
  imei_.ClearToEmpty();
}
inline const std::string& DBRequest::imei() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.imei)
  return _internal_imei();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBRequest::set_imei(ArgT0&& arg0, ArgT... args) {
 
 imei_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBRequest.imei)
}
inline std::string* DBRequest::mutable_imei() {
  std::string* _s = _internal_mutable_imei();
  // @@protoc_insertion_point(field_mutable:game_server.DBRequest.imei)
  return _s;
}
inline const std::string& DBRequest::_internal_imei() const {
  return imei_.Get();
}
inline void DBRequest::_internal_set_imei(const std::string& value) {
  
  imei_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBRequest::_internal_mutable_imei() {
  
  return imei_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBRequest::release_imei() {
  // @@protoc_insertion_point(field_release:game_server.DBRequest.imei)
  return imei_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBRequest::set_allocated_imei(std::string* imei) {
  if (imei != nullptr) {
    
  } else {
    
  }
  imei_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), imei,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (imei_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    imei_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBRequest.imei)
}

// int32 ip = 12;
inline void DBRequest::clear_ip() {
  ip_ = 0;
}
inline int32_t DBRequest::_internal_ip() const {
  return ip_;
}
inline int32_t DBRequest::ip() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.ip)
  return _internal_ip();
}
inline void DBRequest::_internal_set_ip(int32_t value) {
  
  ip_ = value;
}
inline void DBRequest::set_ip(int32_t value) {
  _internal_set_ip(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.ip)
}

// uint64 role_id = 13;
inline void DBRequest::clear_role_id() {
  role_id_ = uint64_t{0u};
}
inline uint64_t DBRequest::_internal_role_id() const {
  return role_id_;
}
inline uint64_t DBRequest::role_id() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.role_id)
  return _internal_role_id();
}
inline void DBRequest::_internal_set_role_id(uint64_t value) {
  
  role_id_ = value;
}
inline void DBRequest::set_role_id(uint64_t value) {
  _internal_set_role_id(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.role_id)
}

// string role_name = 14;
inline void DBRequest::clear_role_name() {
  role_name_.ClearToEmpty();
}
inline const std::string& DBRequest::role_name() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.role_name)
  return _internal_role_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBRequest::set_role_name(ArgT0&& arg0, ArgT... args) {
 
 role_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBRequest.role_name)
}
inline std::string* DBRequest::mutable_role_name() {
  std::string* _s = _internal_mutable_role_name();
  // @@protoc_insertion_point(field_mutable:game_server.DBRequest.role_name)
  return _s;
}
inline const std::string& DBRequest::_internal_role_name() const {
  return role_name_.Get();
}
inline void DBRequest::_internal_set_role_name(const std::string& value) {
  
  role_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBRequest::_internal_mutable_role_name() {
  
  return role_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBRequest::release_role_name() {
  // @@protoc_insertion_point(field_release:game_server.DBRequest.role_name)
  return role_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBRequest::set_allocated_role_name(std::string* role_name) {
  if (role_name != nullptr) {
    
  } else {
    
  }
  role_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), role_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (role_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    role_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBRequest.role_name)
}

// int32 server_id = 15;
inline void DBRequest::clear_server_id() {
  server_id_ = 0;
}
inline int32_t DBRequest::_internal_server_id() const {
  return server_id_;
}
inline int32_t DBRequest::server_id() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.server_id)
  return _internal_server_id();
}
inline void DBRequest::_internal_set_server_id(int32_t value) {
  
  server_id_ = value;
}
inline void DBRequest::set_server_id(int32_t value) {
  _internal_set_server_id(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.server_id)
}

// int32 career = 16;
inline void DBRequest::clear_career() {
  career_ = 0;
}
inline int32_t DBRequest::_internal_career() const {
  return career_;
}
inline int32_t DBRequest::career() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.career)
  return _internal_career();
}
inline void DBRequest::_internal_set_career(int32_t value) {
  
  career_ = value;
}
inline void DBRequest::set_career(int32_t value) {
  _internal_set_career(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.career)
}

// int32 level = 17;
inline void DBRequest::clear_level() {
  level_ = 0;
}
inline int32_t DBRequest::_internal_level() const {
  return level_;
}
inline int32_t DBRequest::level() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.level)
  return _internal_level();
}
inline void DBRequest::_internal_set_level(int32_t value) {
  
  level_ = value;
}
inline void DBRequest::set_level(int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.level)
}

// int64 exp = 18;
inline void DBRequest::clear_exp() {
  exp_ = int64_t{0};
}
inline int64_t DBRequest::_internal_exp() const {
  return exp_;
}
inline int64_t DBRequest::exp() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.exp)
  return _internal_exp();
}
inline void DBRequest::_internal_set_exp(int64_t value) {
  
  exp_ = value;
}
inline void DBRequest::set_exp(int64_t value) {
  _internal_set_exp(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.exp)
}

// int32 head_id = 19;
inline void DBRequest::clear_head_id() {
  head_id_ = 0;
}
inline int32_t DBRequest::_internal_head_id() const {
  return head_id_;
}
inline int32_t DBRequest::head_id() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.head_id)
  return _internal_head_id();
}
inline void DBRequest::_internal_set_head_id(int32_t value) {
  
  head_id_ = value;
}
inline void DBRequest::set_head_id(int32_t value) {
  _internal_set_head_id(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.head_id)
}

// int32 portrait_frame = 20;
inline void DBRequest::clear_portrait_frame() {
  portrait_frame_ = 0;
}
inline int32_t DBRequest::_internal_portrait_frame() const {
  return portrait_frame_;
}
inline int32_t DBRequest::portrait_frame() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.portrait_frame)
  return _internal_portrait_frame();
}
inline void DBRequest::_internal_set_portrait_frame(int32_t value) {
  
  portrait_frame_ = value;
}
inline void DBRequest::set_portrait_frame(int32_t value) {
  _internal_set_portrait_frame(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.portrait_frame)
}

// int32 is_deleted = 21;
inline void DBRequest::clear_is_deleted() {
  is_deleted_ = 0;
}
inline int32_t DBRequest::_internal_is_deleted() const {
  return is_deleted_;
}
inline int32_t DBRequest::is_deleted() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.is_deleted)
  return _internal_is_deleted();
}
inline void DBRequest::_internal_set_is_deleted(int32_t value) {
  
  is_deleted_ = value;
}
inline void DBRequest::set_is_deleted(int32_t value) {
  _internal_set_is_deleted(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.is_deleted)
}

// int64 delete_time = 22;
inline void DBRequest::clear_delete_time() {
  delete_time_ = int64_t{0};
}
inline int64_t DBRequest::_internal_delete_time() const {
  return delete_time_;
}
inline int64_t DBRequest::delete_time() const {
  // @@protoc_insertion_point(field_get:game_server.DBRequest.delete_time)
  return _internal_delete_time();
}
inline void DBRequest::_internal_set_delete_time(int64_t value) {
  
  delete_time_ = value;
}
inline void DBRequest::set_delete_time(int64_t value) {
  _internal_set_delete_time(value);
  // @@protoc_insertion_point(field_set:game_server.DBRequest.delete_time)
}

// -------------------------------------------------------------------

// DBResponse

// int32 ret_code = 1;
inline void DBResponse::clear_ret_code() {
  ret_code_ = 0;
}
inline int32_t DBResponse::_internal_ret_code() const {
  return ret_code_;
}
inline int32_t DBResponse::ret_code() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.ret_code)
  return _internal_ret_code();
}
inline void DBResponse::_internal_set_ret_code(int32_t value) {
  
  ret_code_ = value;
}
inline void DBResponse::set_ret_code(int32_t value) {
  _internal_set_ret_code(value);
  // @@protoc_insertion_point(field_set:game_server.DBResponse.ret_code)
}

// string ret_msg = 2;
inline void DBResponse::clear_ret_msg() {
  ret_msg_.ClearToEmpty();
}
inline const std::string& DBResponse::ret_msg() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.ret_msg)
  return _internal_ret_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBResponse::set_ret_msg(ArgT0&& arg0, ArgT... args) {
 
 ret_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBResponse.ret_msg)
}
inline std::string* DBResponse::mutable_ret_msg() {
  std::string* _s = _internal_mutable_ret_msg();
  // @@protoc_insertion_point(field_mutable:game_server.DBResponse.ret_msg)
  return _s;
}
inline const std::string& DBResponse::_internal_ret_msg() const {
  return ret_msg_.Get();
}
inline void DBResponse::_internal_set_ret_msg(const std::string& value) {
  
  ret_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBResponse::_internal_mutable_ret_msg() {
  
  return ret_msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBResponse::release_ret_msg() {
  // @@protoc_insertion_point(field_release:game_server.DBResponse.ret_msg)
  return ret_msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBResponse::set_allocated_ret_msg(std::string* ret_msg) {
  if (ret_msg != nullptr) {
    
  } else {
    
  }
  ret_msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ret_msg,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ret_msg_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    ret_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBResponse.ret_msg)
}

// uint64 account_id = 3;
inline void DBResponse::clear_account_id() {
  account_id_ = uint64_t{0u};
}
inline uint64_t DBResponse::_internal_account_id() const {
  return account_id_;
}
inline uint64_t DBResponse::account_id() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.account_id)
  return _internal_account_id();
}
inline void DBResponse::_internal_set_account_id(uint64_t value) {
  
  account_id_ = value;
}
inline void DBResponse::set_account_id(uint64_t value) {
  _internal_set_account_id(value);
  // @@protoc_insertion_point(field_set:game_server.DBResponse.account_id)
}

// string account_name = 4;
inline void DBResponse::clear_account_name() {
  account_name_.ClearToEmpty();
}
inline const std::string& DBResponse::account_name() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.account_name)
  return _internal_account_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DBResponse::set_account_name(ArgT0&& arg0, ArgT... args) {
 
 account_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.DBResponse.account_name)
}
inline std::string* DBResponse::mutable_account_name() {
  std::string* _s = _internal_mutable_account_name();
  // @@protoc_insertion_point(field_mutable:game_server.DBResponse.account_name)
  return _s;
}
inline const std::string& DBResponse::_internal_account_name() const {
  return account_name_.Get();
}
inline void DBResponse::_internal_set_account_name(const std::string& value) {
  
  account_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DBResponse::_internal_mutable_account_name() {
  
  return account_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DBResponse::release_account_name() {
  // @@protoc_insertion_point(field_release:game_server.DBResponse.account_name)
  return account_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DBResponse::set_allocated_account_name(std::string* account_name) {
  if (account_name != nullptr) {
    
  } else {
    
  }
  account_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), account_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (account_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    account_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.DBResponse.account_name)
}

// int32 channel = 5;
inline void DBResponse::clear_channel() {
  channel_ = 0;
}
inline int32_t DBResponse::_internal_channel() const {
  return channel_;
}
inline int32_t DBResponse::channel() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.channel)
  return _internal_channel();
}
inline void DBResponse::_internal_set_channel(int32_t value) {
  
  channel_ = value;
}
inline void DBResponse::set_channel(int32_t value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:game_server.DBResponse.channel)
}

// int64 create_time = 6;
inline void DBResponse::clear_create_time() {
  create_time_ = int64_t{0};
}
inline int64_t DBResponse::_internal_create_time() const {
  return create_time_;
}
inline int64_t DBResponse::create_time() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.create_time)
  return _internal_create_time();
}
inline void DBResponse::_internal_set_create_time(int64_t value) {
  
  create_time_ = value;
}
inline void DBResponse::set_create_time(int64_t value) {
  _internal_set_create_time(value);
  // @@protoc_insertion_point(field_set:game_server.DBResponse.create_time)
}

// int64 last_login_time = 7;
inline void DBResponse::clear_last_login_time() {
  last_login_time_ = int64_t{0};
}
inline int64_t DBResponse::_internal_last_login_time() const {
  return last_login_time_;
}
inline int64_t DBResponse::last_login_time() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.last_login_time)
  return _internal_last_login_time();
}
inline void DBResponse::_internal_set_last_login_time(int64_t value) {
  
  last_login_time_ = value;
}
inline void DBResponse::set_last_login_time(int64_t value) {
  _internal_set_last_login_time(value);
  // @@protoc_insertion_point(field_set:game_server.DBResponse.last_login_time)
}

// int32 last_login_ip = 8;
inline void DBResponse::clear_last_login_ip() {
  last_login_ip_ = 0;
}
inline int32_t DBResponse::_internal_last_login_ip() const {
  return last_login_ip_;
}
inline int32_t DBResponse::last_login_ip() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.last_login_ip)
  return _internal_last_login_ip();
}
inline void DBResponse::_internal_set_last_login_ip(int32_t value) {
  
  last_login_ip_ = value;
}
inline void DBResponse::set_last_login_ip(int32_t value) {
  _internal_set_last_login_ip(value);
  // @@protoc_insertion_point(field_set:game_server.DBResponse.last_login_ip)
}

// bool is_sealed = 9;
inline void DBResponse::clear_is_sealed() {
  is_sealed_ = false;
}
inline bool DBResponse::_internal_is_sealed() const {
  return is_sealed_;
}
inline bool DBResponse::is_sealed() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.is_sealed)
  return _internal_is_sealed();
}
inline void DBResponse::_internal_set_is_sealed(bool value) {
  
  is_sealed_ = value;
}
inline void DBResponse::set_is_sealed(bool value) {
  _internal_set_is_sealed(value);
  // @@protoc_insertion_point(field_set:game_server.DBResponse.is_sealed)
}

// int64 seal_end_time = 10;
inline void DBResponse::clear_seal_end_time() {
  seal_end_time_ = int64_t{0};
}
inline int64_t DBResponse::_internal_seal_end_time() const {
  return seal_end_time_;
}
inline int64_t DBResponse::seal_end_time() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.seal_end_time)
  return _internal_seal_end_time();
}
inline void DBResponse::_internal_set_seal_end_time(int64_t value) {
  
  seal_end_time_ = value;
}
inline void DBResponse::set_seal_end_time(int64_t value) {
  _internal_set_seal_end_time(value);
  // @@protoc_insertion_point(field_set:game_server.DBResponse.seal_end_time)
}

// bool review = 11;
inline void DBResponse::clear_review() {
  review_ = false;
}
inline bool DBResponse::_internal_review() const {
  return review_;
}
inline bool DBResponse::review() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.review)
  return _internal_review();
}
inline void DBResponse::_internal_set_review(bool value) {
  
  review_ = value;
}
inline void DBResponse::set_review(bool value) {
  _internal_set_review(value);
  // @@protoc_insertion_point(field_set:game_server.DBResponse.review)
}

// repeated .game_server.RoleInfo role_list = 12;
inline int DBResponse::_internal_role_list_size() const {
  return role_list_.size();
}
inline int DBResponse::role_list_size() const {
  return _internal_role_list_size();
}
inline void DBResponse::clear_role_list() {
  role_list_.Clear();
}
inline ::game_server::RoleInfo* DBResponse::mutable_role_list(int index) {
  // @@protoc_insertion_point(field_mutable:game_server.DBResponse.role_list)
  return role_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game_server::RoleInfo >*
DBResponse::mutable_role_list() {
  // @@protoc_insertion_point(field_mutable_list:game_server.DBResponse.role_list)
  return &role_list_;
}
inline const ::game_server::RoleInfo& DBResponse::_internal_role_list(int index) const {
  return role_list_.Get(index);
}
inline const ::game_server::RoleInfo& DBResponse::role_list(int index) const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.role_list)
  return _internal_role_list(index);
}
inline ::game_server::RoleInfo* DBResponse::_internal_add_role_list() {
  return role_list_.Add();
}
inline ::game_server::RoleInfo* DBResponse::add_role_list() {
  ::game_server::RoleInfo* _add = _internal_add_role_list();
  // @@protoc_insertion_point(field_add:game_server.DBResponse.role_list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::game_server::RoleInfo >&
DBResponse::role_list() const {
  // @@protoc_insertion_point(field_list:game_server.DBResponse.role_list)
  return role_list_;
}

// .game_server.RoleInfo role_info = 13;
inline bool DBResponse::_internal_has_role_info() const {
  return this != internal_default_instance() && role_info_ != nullptr;
}
inline bool DBResponse::has_role_info() const {
  return _internal_has_role_info();
}
inline void DBResponse::clear_role_info() {
  if (GetArenaForAllocation() == nullptr && role_info_ != nullptr) {
    delete role_info_;
  }
  role_info_ = nullptr;
}
inline const ::game_server::RoleInfo& DBResponse::_internal_role_info() const {
  const ::game_server::RoleInfo* p = role_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::game_server::RoleInfo&>(
      ::game_server::_RoleInfo_default_instance_);
}
inline const ::game_server::RoleInfo& DBResponse::role_info() const {
  // @@protoc_insertion_point(field_get:game_server.DBResponse.role_info)
  return _internal_role_info();
}
inline void DBResponse::unsafe_arena_set_allocated_role_info(
    ::game_server::RoleInfo* role_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(role_info_);
  }
  role_info_ = role_info;
  if (role_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game_server.DBResponse.role_info)
}
inline ::game_server::RoleInfo* DBResponse::release_role_info() {
  
  ::game_server::RoleInfo* temp = role_info_;
  role_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::game_server::RoleInfo* DBResponse::unsafe_arena_release_role_info() {
  // @@protoc_insertion_point(field_release:game_server.DBResponse.role_info)
  
  ::game_server::RoleInfo* temp = role_info_;
  role_info_ = nullptr;
  return temp;
}
inline ::game_server::RoleInfo* DBResponse::_internal_mutable_role_info() {
  
  if (role_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::game_server::RoleInfo>(GetArenaForAllocation());
    role_info_ = p;
  }
  return role_info_;
}
inline ::game_server::RoleInfo* DBResponse::mutable_role_info() {
  ::game_server::RoleInfo* _msg = _internal_mutable_role_info();
  // @@protoc_insertion_point(field_mutable:game_server.DBResponse.role_info)
  return _msg;
}
inline void DBResponse::set_allocated_role_info(::game_server::RoleInfo* role_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete role_info_;
  }
  if (role_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::game_server::RoleInfo>::GetOwningArena(role_info);
    if (message_arena != submessage_arena) {
      role_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, role_info, submessage_arena);
    }
    
  } else {
    
  }
  role_info_ = role_info;
  // @@protoc_insertion_point(field_set_allocated:game_server.DBResponse.role_info)
}

// -------------------------------------------------------------------

// RoleInfo

// uint64 role_id = 1;
inline void RoleInfo::clear_role_id() {
  role_id_ = uint64_t{0u};
}
inline uint64_t RoleInfo::_internal_role_id() const {
  return role_id_;
}
inline uint64_t RoleInfo::role_id() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.role_id)
  return _internal_role_id();
}
inline void RoleInfo::_internal_set_role_id(uint64_t value) {
  
  role_id_ = value;
}
inline void RoleInfo::set_role_id(uint64_t value) {
  _internal_set_role_id(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.role_id)
}

// uint64 account_id = 2;
inline void RoleInfo::clear_account_id() {
  account_id_ = uint64_t{0u};
}
inline uint64_t RoleInfo::_internal_account_id() const {
  return account_id_;
}
inline uint64_t RoleInfo::account_id() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.account_id)
  return _internal_account_id();
}
inline void RoleInfo::_internal_set_account_id(uint64_t value) {
  
  account_id_ = value;
}
inline void RoleInfo::set_account_id(uint64_t value) {
  _internal_set_account_id(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.account_id)
}

// int32 server_id = 3;
inline void RoleInfo::clear_server_id() {
  server_id_ = 0;
}
inline int32_t RoleInfo::_internal_server_id() const {
  return server_id_;
}
inline int32_t RoleInfo::server_id() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.server_id)
  return _internal_server_id();
}
inline void RoleInfo::_internal_set_server_id(int32_t value) {
  
  server_id_ = value;
}
inline void RoleInfo::set_server_id(int32_t value) {
  _internal_set_server_id(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.server_id)
}

// string role_name = 4;
inline void RoleInfo::clear_role_name() {
  role_name_.ClearToEmpty();
}
inline const std::string& RoleInfo::role_name() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.role_name)
  return _internal_role_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoleInfo::set_role_name(ArgT0&& arg0, ArgT... args) {
 
 role_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.role_name)
}
inline std::string* RoleInfo::mutable_role_name() {
  std::string* _s = _internal_mutable_role_name();
  // @@protoc_insertion_point(field_mutable:game_server.RoleInfo.role_name)
  return _s;
}
inline const std::string& RoleInfo::_internal_role_name() const {
  return role_name_.Get();
}
inline void RoleInfo::_internal_set_role_name(const std::string& value) {
  
  role_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RoleInfo::_internal_mutable_role_name() {
  
  return role_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RoleInfo::release_role_name() {
  // @@protoc_insertion_point(field_release:game_server.RoleInfo.role_name)
  return role_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RoleInfo::set_allocated_role_name(std::string* role_name) {
  if (role_name != nullptr) {
    
  } else {
    
  }
  role_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), role_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (role_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    role_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_server.RoleInfo.role_name)
}

// int32 career = 5;
inline void RoleInfo::clear_career() {
  career_ = 0;
}
inline int32_t RoleInfo::_internal_career() const {
  return career_;
}
inline int32_t RoleInfo::career() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.career)
  return _internal_career();
}
inline void RoleInfo::_internal_set_career(int32_t value) {
  
  career_ = value;
}
inline void RoleInfo::set_career(int32_t value) {
  _internal_set_career(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.career)
}

// int32 level = 6;
inline void RoleInfo::clear_level() {
  level_ = 0;
}
inline int32_t RoleInfo::_internal_level() const {
  return level_;
}
inline int32_t RoleInfo::level() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.level)
  return _internal_level();
}
inline void RoleInfo::_internal_set_level(int32_t value) {
  
  level_ = value;
}
inline void RoleInfo::set_level(int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.level)
}

// int64 exp = 7;
inline void RoleInfo::clear_exp() {
  exp_ = int64_t{0};
}
inline int64_t RoleInfo::_internal_exp() const {
  return exp_;
}
inline int64_t RoleInfo::exp() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.exp)
  return _internal_exp();
}
inline void RoleInfo::_internal_set_exp(int64_t value) {
  
  exp_ = value;
}
inline void RoleInfo::set_exp(int64_t value) {
  _internal_set_exp(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.exp)
}

// int32 head_id = 8;
inline void RoleInfo::clear_head_id() {
  head_id_ = 0;
}
inline int32_t RoleInfo::_internal_head_id() const {
  return head_id_;
}
inline int32_t RoleInfo::head_id() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.head_id)
  return _internal_head_id();
}
inline void RoleInfo::_internal_set_head_id(int32_t value) {
  
  head_id_ = value;
}
inline void RoleInfo::set_head_id(int32_t value) {
  _internal_set_head_id(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.head_id)
}

// int32 portrait_frame = 9;
inline void RoleInfo::clear_portrait_frame() {
  portrait_frame_ = 0;
}
inline int32_t RoleInfo::_internal_portrait_frame() const {
  return portrait_frame_;
}
inline int32_t RoleInfo::portrait_frame() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.portrait_frame)
  return _internal_portrait_frame();
}
inline void RoleInfo::_internal_set_portrait_frame(int32_t value) {
  
  portrait_frame_ = value;
}
inline void RoleInfo::set_portrait_frame(int32_t value) {
  _internal_set_portrait_frame(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.portrait_frame)
}

// int64 create_time = 10;
inline void RoleInfo::clear_create_time() {
  create_time_ = int64_t{0};
}
inline int64_t RoleInfo::_internal_create_time() const {
  return create_time_;
}
inline int64_t RoleInfo::create_time() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.create_time)
  return _internal_create_time();
}
inline void RoleInfo::_internal_set_create_time(int64_t value) {
  
  create_time_ = value;
}
inline void RoleInfo::set_create_time(int64_t value) {
  _internal_set_create_time(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.create_time)
}

// int64 last_login_time = 11;
inline void RoleInfo::clear_last_login_time() {
  last_login_time_ = int64_t{0};
}
inline int64_t RoleInfo::_internal_last_login_time() const {
  return last_login_time_;
}
inline int64_t RoleInfo::last_login_time() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.last_login_time)
  return _internal_last_login_time();
}
inline void RoleInfo::_internal_set_last_login_time(int64_t value) {
  
  last_login_time_ = value;
}
inline void RoleInfo::set_last_login_time(int64_t value) {
  _internal_set_last_login_time(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.last_login_time)
}

// int32 is_deleted = 12;
inline void RoleInfo::clear_is_deleted() {
  is_deleted_ = 0;
}
inline int32_t RoleInfo::_internal_is_deleted() const {
  return is_deleted_;
}
inline int32_t RoleInfo::is_deleted() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.is_deleted)
  return _internal_is_deleted();
}
inline void RoleInfo::_internal_set_is_deleted(int32_t value) {
  
  is_deleted_ = value;
}
inline void RoleInfo::set_is_deleted(int32_t value) {
  _internal_set_is_deleted(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.is_deleted)
}

// int64 delete_time = 13;
inline void RoleInfo::clear_delete_time() {
  delete_time_ = int64_t{0};
}
inline int64_t RoleInfo::_internal_delete_time() const {
  return delete_time_;
}
inline int64_t RoleInfo::delete_time() const {
  // @@protoc_insertion_point(field_get:game_server.RoleInfo.delete_time)
  return _internal_delete_time();
}
inline void RoleInfo::_internal_set_delete_time(int64_t value) {
  
  delete_time_ = value;
}
inline void RoleInfo::set_delete_time(int64_t value) {
  _internal_set_delete_time(value);
  // @@protoc_insertion_point(field_set:game_server.RoleInfo.delete_time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_server

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::game_server::DBOperationType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_server::DBOperationType>() {
  return ::game_server::DBOperationType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_5fdb_2eproto
